// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animWrap': string;
  'black': string;
  'red': string;
  'textLabel': string;
  'transparent': string;
}
export const cssExports: CssExports;
export default cssExports;
